### ISSUE TITLE
Issue with Yarn workspaces

### ISSUE THREAD

**Issue by karthikcodes6** [belgattitude/nextjs-monorepo-example#776]
I tried to install the dependencies using `yarn` I'm getting below errors

Yarn: 1.22.11
Node: v14.18.1
OS: MacOS

```
Error: Couldn't find package "@your-org/ui-lib@workspace:*" required by "blog-app@3.20.1" on the "npm" registry.
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:38129:17
    at Generator.throw (<anonymous>)
    at step (/Users/karthik/.yarn/releases/yarn-1.22.11.cjs:310:30)
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@your-org/ui-lib@workspace:*" required by "vite-app@0.1.0" on the "npm" registry.
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:38129:17
    at Generator.throw (<anonymous>)
    at step (/Users/karthik/.yarn/releases/yarn-1.22.11.cjs:310:30)
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@your-org/ui-lib@workspace:*" required by "web-app@3.34.1" on the "npm" registry.
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:38129:17
    at Generator.throw (<anonymous>)
    at step (/Users/karthik/.yarn/releases/yarn-1.22.11.cjs:310:30)
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@your-org/core-lib@workspace:*" required by "vite-app@0.1.0" on the "npm" registry.
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:38129:17
    at Generator.throw (<anonymous>)
    at step (/Users/karthik/.yarn/releases/yarn-1.22.11.cjs:310:30)
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@your-org/db-main-prisma@workspace:*" required by "web-app@3.34.1" on the "npm" registry.
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:38129:17
    at Generator.throw (<anonymous>)
    at step (/Users/karthik/.yarn/releases/yarn-1.22.11.cjs:310:30)
    at /Users/karthik/.yarn/releases/yarn-1.22.11.cjs:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@your-org/core-lib@workspace:*" required by "web-app@3.34.1" on the "npm" registry.
    at /Users/karthik/.yarn/releases/yarn-1.2
```

**Comment by karthikcodes6** [comment]
Cool. It was because of the cache. Yarn was picking the version from my home folder cache instead from the project level cache. It started to work after I cleared the home folder cache. Thank you so much for your help 😊.

**Comment by belgattitude** [comment]
Ah yes thanks for letting me know.  Happy day
